### PR TITLE
contact form

### PR DESCRIPTION
**Pull request by JackMwisa**
**Adding a contact form to my project**

### CODE REVIEW

**Review by Moh9998 — APPROVED** [review]
well done on this project there is nothing left to say other than its time to merge it

**Review by HAMMAS-SALEEM — COMMENTED** [review]
# Invalid Pull Request :red_circle: 

**_You have put a lot of effort into your project but I guess you have been confused between the links. Please submit this project from the right link on your dashboard :+1:_**

**Review by Reem-lab — APPROVED** [review]
# Hi @JackMwisa, 👏🏻👏🏻 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🔥🔥 


## Highlights
- No Linters error .✅✅
- Good follow GitHub flow ✅✅✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by JackMwisa** [comment]
Thank you @Reem-lab @Moh9998 @HAMMAS-SALEEM

**Pull request merged**
